name: Storybook
on:
  push:
    branches:
      - master # if any push happens on branch `main`, run this workflow. You could also add `paths` to detect changes in specific folder
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies and build Storybook
        run: | 
          npm install 
          npm run build-storybook
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./docs/storybook
  
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v2